version: '2.1'

orbs:
  nix: eld/nix@1.0.0

jobs:
  build_test:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - nix/install
      - checkout
      - run:
          name: Run tests
          command: |
            nix-shell shell.nix --command "pytest"
  pypi_publish:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            pip3 install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -U twine wheel setuptools
            python3 setup.py sdist bdist_wheel
            twine check dist/*
            twine upload dist/*
            deactivate

workflows:
  build_test_publish:
    jobs:
      - build_test:
          filters:
            tags:
              only: /.*/
      - pypi_publish:
          requires:
            - build_test
          filters:
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/
