version: 2.1
orbs:
  nix: eld/nix@1.0.0
jobs:
  install-nix:
    steps:
      - nix/install
  build_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get upgrade
      - run:
          name: Run tests
          command: |
            cat >shell.nix <<'EOF'
            { pkgs ? import <nixpkgs> {} }:
            let
            
              mutwo-abjad-archive = builtins.fetchTarball "https://github.com/mutwo-org/mutwo.abjad/archive/main.tar.gz";
              mutwo-abjad = import (mutwo-abjad-archive + "/default.nix");
            
              myPython = pkgs.python310.buildEnv.override {
                extraLibs = with pkgs; [
                  mutwo-abjad
                ];
              };
            
            in
            
              pkgs.mkShell {
                buildInputs = with pkgs; [
                  myPython
                ];
              }
            EOF
            nix-shell shell.nix
            pytest
  pypi_publish:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            pip3 install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -U twine wheel setuptools
            python3 setup.py sdist bdist_wheel
            twine check dist/*
            twine upload dist/*
            deactivate

workflows:
  build_test_publish:
    jobs:
      - install-nix
      - build_test:
          filters:
            tags:
              only: /.*/
      - pypi_publish:
          requires:
            - build_test
          filters:
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/
