version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get upgrade
      - run: wget https://lilypond.org/download/binaries/linux-64/lilypond-2.23.6-1.linux-64.sh && sh lilypond-2.23.6-1.linux-64.sh --batch
      - run:
          name: Run tests
          command: |
            sudo apt-get install espeak-ng mbrola mbrola-en1
            pip3 install virtualenv
            TEST_VIRTUALENV_DIR=mutwo_test
            mkdir $TEST_VIRTUALENV_DIR
            virtualenv $TEST_VIRTUALENV_DIR/mutwo_test
            source $TEST_VIRTUALENV_DIR/mutwo_test/bin/activate
            pip3 install .[testing]
            pytest
            deactivate
  pypi_publish:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            pip3 install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -U twine wheel setuptools
            python3 setup.py sdist bdist_wheel
            twine check dist/*
            twine upload dist/*
            deactivate

workflows:
  build_test_publish:
    jobs:
      - build_test:
          filters:
            tags:
              only: /.*/
      - pypi_publish:
          requires:
            - build_test
          filters:
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/
